# Basic Site Settings
title                    : "Prisha Srivastava"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
  # Biographic information
logo          : "/images/profile pic.png"
name             : "Prisha Srivastava"
pronouns         : she/her 
description              : "Post Graduate Student pursuing Masters in Business Analytics from University of Cincinnati."
location         : India
email            : prishas.2501@gmail.com

  # Academic websites

  
  # Social media
linkedin         : prisha-srivastava
  
theme: jekyll-theme-chirpy

#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
